[project]
name = "part1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fpgrowth-py>=1.0.0",
    "mlxtend>=0.23.4",
    "pandas>=2.2.3",
]
